SELECT D.HACKER_ID, D.NAME, SUM(D.SCORE) FROM 
(SELECT H.HACKER_ID, H.NAME, MAX(SCORE) SCORE FROM SUBMISSIONS S
INNER JOIN HACKERS H ON (H.HACKER_ID = S.HACKER_ID)
GROUP BY H.NAME, H.HACKER_ID, CHALLENGE_ID) D
GROUP BY D.HACKER_ID, D.NAME
HAVING SUM(D.SCORE) > 0
ORDER BY 3 DESC, 1 ASC;